MODEL_PATH = "/root/base_model/qwen2"
LOG_PATH = "/root/tf-logs"
OUTPUT_PATH = "/root/autodl-tmp/pt_output/results"
MODEL_OUTPUT_PATH = "/root/autodl-tmp/pt_output/final_model"
DS_CONFIG_PATH = "./ds_config.json"
DATA_DIR = "../../../data/mini_pt_train_data/"