MODEL_PATH = "/root/autodl-tmp/pt_output/final_model"
LOG_PATH = "/root/tf-logs"
OUTPUT_PATH = "/root/autodl-tmp/sft_output/results"
MODEL_OUTPUT_PATH = "/root/autodl-tmp/sft_output/final_model"
DS_CONFIG_PATH = "./ds_config.json"
DATA_DIR = "../../../data/mini_sft_train_data/"